spring.application.name: review-service

server.port: 7004

server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
# This configuration is also required for PersistenceTests annotated with @DataJpaTest
spring.jpa.hibernate.ddl-auto: update

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG

---

spring.config.activate.on-profile: docker
server.port: 8080    